import { IndoorPlant } from "./interfaces/indoor-plant.interface";

export const indoorPlantsList: IndoorPlant[] = [
    {
        id: '1',
        name: 'Snake Plant',
        scientificName: 'Sansevieria trifasciata',
        image: 'https://images.pexels.com/photos/2123482/pexels-photo-2123482.jpeg',
        careLevel: 'Easy',
        light: 'Low',
        waterFrequency: 18,
        waterVolume: 150,
        fertilizer: 'DCM Houseplant Fertiliser or Westland Feed All Purpose',
        nutritionFrequency: 30,
        soilType: 'Well-draining, sandy soil',
        notes: 'Tolerates low light and infrequent watering.',
    },
    {
        id: '2',
        name: 'Peace Lily',
        scientificName: 'Spathiphyllum wallisii',
        image: 'https://sargentsgardens.com/wp-content/uploads/2024/12/Photo-Dec-17-2024-10-00-28-AM-scaled.jpg',
        careLevel: 'Easy',
        light: 'Medium',
        waterFrequency: 7,
        waterVolume: 200,
        fertilizer: 'Miracle-Gro Indoor Plant Food or Westland Houseplant Feed',
        nutritionFrequency: 14,
        soilType: 'Peat-based, well-aerated potting mix',
        notes: 'Prefers humid conditions and indirect light.',
    },
    {
        id: '3',
        name: 'Spider Plant',
        scientificName: 'Chlorophytum comosum',
        image: 'https://media.houseandgarden.co.uk/photos/66e02c4143ff56cb528fe5b6/master/w_1600,c_limit/08-01-24-HG-Crisp242.jpg',
        careLevel: 'Easy',
        light: 'Bright',
        waterFrequency: 7,
        waterVolume: 150,
        fertilizer: 'Westland Feed All Purpose or Baby Bio Houseplant Food',
        nutritionFrequency: 25,
        soilType: 'Loamy, well-draining soil',
        notes: 'Produces offshoots that can be propagated easily.',
    },
    {
        id: '4',
        name: 'Aloe Vera',
        scientificName: 'Aloe vera',
        image: 'https://gardeningsg.nparks.gov.sg/images/Plants/aloevera5_jacquelinechua.jpg',
        careLevel: 'Easy',
        light: 'Bright',
        waterFrequency: 21,
        waterVolume: 120,
        fertilizer: 'DCM Cactus & Succulent Feed or Vitax Houseplant Feed',
        nutritionFrequency: 42,
        soilType: 'Cactus mix or sandy potting soil',
        notes: 'Do not overwater; allow soil to dry completely.',
    },
    {
        id: '5',
        name: 'ZZ Plant',
        scientificName: 'Zamioculcas zamiifolia',
        image: 'https://glasswingshop.com/cdn/shop/products/8D2A2069.jpg?v=1595400475&width=940',
        careLevel: 'Easy',
        light: 'Low',
        waterFrequency: 21,
        waterVolume: 100,
        fertilizer: 'Vitax Indoor Plant Feed or Westland All Purpose',
        nutritionFrequency: 30,
        soilType: 'Well-drained loamy soil',
        notes: 'Thrives on neglect, ideal for low-light spaces.',
    },
    {
        id: '6',
        name: 'Pothos',
        scientificName: 'Epipremnum aureum',
        image: 'https://interiorplants.ca/wp-content/uploads/2023/09/pothos-jade-satin-6in-1-1536x1536.jpg',
        careLevel: 'Easy',
        light: 'Medium',
        waterFrequency: 6,
        waterVolume: 180,
        fertilizer: 'Baby Bio Houseplant Food or Miracle-Gro Indoor',
        nutritionFrequency: 20,
        soilType: 'Peaty, well-drained soil',
        notes: 'Fast-growing vine; great for hanging baskets.',
    },
    {
        id: '7',
        name: 'Philodendron',
        scientificName: 'Philodendron hederaceum',
        image: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTTpw0Ebkuq9gTXYatNShJlDjAJoacnjgAA50igfedK8WDRxEW79999prfRhYKKogS-HAmMC89oW9rlKg5Y8v_Vlw',
        careLevel: 'Moderate',
        light: 'Medium',
        waterFrequency: 6,
        waterVolume: 200,
        fertilizer: 'Westland or Baby Bio',
        nutritionFrequency: 21,
        soilType: 'Rich, loose potting soil with peat',
        notes: 'Loves humidity and indirect light.',
    },
    {
        id: '8',
        name: 'Fiddle Leaf Fig',
        scientificName: 'Ficus lyrata',
        image: 'https://bloomscape.com/wp-content/uploads/2025/04/self-watering-slate-xxl-fiddle-leaf-fig.png?ver=1096531',
        careLevel: 'Advanced',
        light: 'Bright',
        waterFrequency: 10,
        waterVolume: 300,
        fertilizer: 'DCM Liquid Plant Food or Baby Bio',
        nutritionFrequency: 15,
        soilType: 'Loamy, fast-draining soil with bark',
        notes: 'Needs bright light and consistent watering.',
    },
    {
        id: '9',
        name: 'Rubber Plant',
        scientificName: 'Ficus elastica',
        image: 'https://www.ladybirdnursery.com.au/wp-content/uploads/0004362_tineke-variegated-rubber-tree.jpeg.webp',
        careLevel: 'Moderate',
        light: 'Medium',
        waterFrequency: 10,
        waterVolume: 250,
        fertilizer: 'Miracle-Gro Liquid Plant Food or Westland',
        nutritionFrequency: 21,
        soilType: 'Loamy soil with coco coir or peat',
        notes: 'Wipe leaves regularly to prevent dust buildup.',
    },
    {
        id: '10',
        name: 'Dracaena',
        scientificName: 'Dracaena marginata',
        image: 'https://hips.hearstapps.com/hmg-prod/images/dracaena-plant-care-66578f39338ba.jpg?crop=1.00xw:1.00xh;0,0&resize=1200:*',
        careLevel: 'Moderate',
        light: 'Medium',
        waterFrequency: 12,
        waterVolume: 180,
        fertilizer: 'Westland Houseplant Feed or Baby Bio',
        nutritionFrequency: 30,
        soilType: 'Rich but well-drained potting soil',
        notes: 'Avoid fluoride-heavy water; sensitive to salts.',
    },
    {
        id: '11',
        name: 'Chinese Evergreen',
        scientificName: 'Aglaonema commutatum',
        image: 'https://www.gardendesign.com/pictures/images/320x240Exact_0x0/site_3/igneous-timeless-tides-chinese-evergreen-aglaonema-commutatum-proven-winners_19182.jpg',
        careLevel: 'Easy',
        light: 'Low',
        waterFrequency: 10,
        waterVolume: 170,
        fertilizer: 'Miracle-Gro Indoor or Baby Bio',
        nutritionFrequency: 30,
        soilType: 'Peat-based, moisture-retaining soil',
        notes: 'Great for low-light offices or bedrooms.',
    },
    {
        id: '12',
        name: 'Calathea',
        scientificName: 'Calathea orbifolia',
        image: 'https://thenunheadgardener.com/wp-content/uploads/images/28000000000000839-1.jpg',
        careLevel: 'Advanced',
        light: 'Low',
        waterFrequency: 5,
        waterVolume: 220,
        fertilizer: 'DCM or Westland All Purpose',
        nutritionFrequency: 20,
        soilType: 'Peaty, high-humidity mix with perlite',
        notes: 'Leaves move daily with light exposure.',
    },
    {
        id: '13',
        name: 'Monstera',
        scientificName: 'Monstera deliciosa',
        image: 'https://images.squarespace-cdn.com/content/v1/56923fa6a976af0bfc533475/4487beac-be01-4ad5-8133-3276fb81972b/IMG_7938.jpg?format=2500w',
        careLevel: 'Moderate',
        light: 'Medium',
        waterFrequency: 7,
        waterVolume: 250,
        fertilizer: 'Baby Bio or DCM Organic Liquid Feed',
        nutritionFrequency: 21,
        soilType: 'Aroid mix: peat, bark, perlite',
        notes: 'Loves space and support for climbing.',
    },
    {
        id: '14',
        name: 'Boston Fern',
        scientificName: 'Nephrolepis exaltata',
        image: 'https://asset.bloomnation.com/c_pad,d_vendor:global:catalog:product:image.png,f_auto,fl_preserve_transparency,q_auto,w_1400/v1720646402/vendor/3628/catalog/product/2/0/20220628043840_file_62bb2e9000d3c_62bb2fd5e2671.jpg',
        careLevel: 'Moderate',
        light: 'Medium',
        waterFrequency: 4,
        waterVolume: 300,
        fertilizer: 'Vitax Liquid Houseplant Food',
        nutritionFrequency: 14,
        soilType: 'Peat-based, high-humidity mix',
        notes: 'Needs misting and frequent watering.',
    },
    {
        id: '15',
        name: 'Jade Plant',
        scientificName: 'Crassula ovata',
        image: 'https://hips.hearstapps.com/hmg-prod/images/beautiful-crassula-ovata-jade-plant-money-plant-royalty-free-image-1722349156.jpg?crop=0.668xw:1.00xh;0.194xw,0&resize=1120:*',
        careLevel: 'Easy',
        light: 'Bright',
        waterFrequency: 15,
        waterVolume: 120,
        fertilizer: 'DCM Cactus & Succulent Feed',
        nutritionFrequency: 30,
        soilType: 'Cactus mix or sandy soil',
        notes: 'Allow soil to dry between waterings.',
    },
    {
        id: '16',
        name: 'Chinese Money Plant',
        scientificName: 'Pilea peperomioides',
        image: 'https://images.unsplash.com/photo-1586194768530-07cf3fa5b4f1?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Easy',
        light: 'Bright indirect',
        waterFrequency: 7,
        waterVolume: 150,
        fertilizer: 'Diluted balanced liquid feed',
        nutritionFrequency: 30,
        soilType: 'Well-draining, peat-based mix',
        notes: 'Known for its coin-shaped leaves and easy propagation.'
    },
    {
        id: '17',
        name: 'Cast Iron Plant',
        scientificName: 'Aspidistra elatior',
        image: 'https://images.unsplash.com/photo-1631116765093-7fb99ffd7cf9?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Easy',
        light: 'Low',
        waterFrequency: 14,
        waterVolume: 200,
        fertilizer: 'Monthly general houseplant feed',
        nutritionFrequency: 30,
        soilType: 'Loamy, well-draining soil',
        notes: 'Highly tolerant of neglect and low light.'
    },
    {
        id: '18',
        name: 'Anthurium',
        scientificName: 'Anthurium andraeanum',
        image: 'https://images.unsplash.com/photo-1544508992-a69ade1a4e8c?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright indirect',
        waterFrequency: 7,
        waterVolume: 180,
        fertilizer: 'High-phosphorus bloom booster',
        nutritionFrequency: 21,
        soilType: 'Coarse, well-draining orchid mix',
        notes: 'Striking red or pink waxy flowers.'
    },
    {
        id: '19',
        name: 'Parlor Palm',
        scientificName: 'Chamaedorea elegans',
        image: 'https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Easy',
        light: 'Low',
        waterFrequency: 10,
        waterVolume: 180,
        fertilizer: 'Weak balanced liquid feed',
        nutritionFrequency: 30,
        soilType: 'Peat-based, well-draining mix',
        notes: 'Excellent for indoor air quality.'
    },
    {
        id: '20',
        name: 'Croton',
        scientificName: 'Codiaeum variegatum',
        image: 'https://images.unsplash.com/photo-1606645289827-8c3e4b1a3b98?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright',
        waterFrequency: 5,
        waterVolume: 200,
        fertilizer: 'Balanced indoor fertilizer',
        nutritionFrequency: 21,
        soilType: 'Rich, fast-draining mix',
        notes: 'Colorful foliage needs high light to thrive.'
    },
    {
        id: '21',
        name: 'Areca Palm',
        scientificName: 'Dypsis lutescens',
        image: 'https://images.unsplash.com/photo-1463320726281-696a485928c7?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Medium',
        waterFrequency: 6,
        waterVolume: 250,
        fertilizer: 'Palm-specific fertilizer',
        nutritionFrequency: 20,
        soilType: 'Loamy, slightly acidic mix',
        notes: 'Adds tropical vibe; prefers humidity.'
    },
    {
        id: '22',
        name: 'English Ivy',
        scientificName: 'Hedera helix',
        image: 'https://images.unsplash.com/photo-1606059755217-5a82dd542cc4?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright indirect',
        waterFrequency: 5,
        waterVolume: 150,
        fertilizer: 'Diluted general fertilizer',
        nutritionFrequency: 21,
        soilType: 'Rich, well-drained potting soil',
        notes: 'Good for hanging pots and shelves.'
    },
    {
        id: '23',
        name: 'Norfolk Island Pine',
        scientificName: 'Araucaria heterophylla',
        image: 'https://images.unsplash.com/photo-1544986581-efac024faf62?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright',
        waterFrequency: 7,
        waterVolume: 200,
        fertilizer: 'All-purpose fertilizer biweekly',
        nutritionFrequency: 14,
        soilType: 'Sandy, slightly acidic mix',
        notes: 'Looks like a mini pine tree.'
    },
    {
        id: '24',
        name: 'Prayer Plant',
        scientificName: 'Maranta leuconeura',
        image: 'https://images.unsplash.com/photo-1582821431309-317c09bb1a75?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Low to medium',
        waterFrequency: 5,
        waterVolume: 170,
        fertilizer: 'Weak liquid fertilizer',
        nutritionFrequency: 21,
        soilType: 'Peaty, moist mix with perlite',
        notes: 'Leaves fold upward at night.'
    },
    {
        id: '25',
        name: 'Lucky Bamboo',
        scientificName: 'Dracaena sanderiana',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Easy',
        light: 'Low to medium',
        waterFrequency: 10,
        waterVolume: 100,
        fertilizer: 'Hydroponic nutrient solution',
        nutritionFrequency: 30,
        soilType: 'Water or moist pebbles',
        notes: 'Often grown in water, symbol of good luck.'
    },
    {
        id: '26',
        name: 'Purple Shamrock',
        scientificName: 'Oxalis triangularis',
        image: 'https://images.unsplash.com/photo-1614592656837-11b46bc26b5b?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright indirect',
        waterFrequency: 6,
        waterVolume: 180,
        fertilizer: 'Balanced liquid fertilizer',
        nutritionFrequency: 30,
        soilType: 'Loamy, well-draining soil',
        notes: 'Purple leaves open and close with light.'
    },
    {
        id: '27',
        name: 'Umbrella Plant',
        scientificName: 'Schefflera arboricola',
        image: 'https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Medium to bright',
        waterFrequency: 7,
        waterVolume: 200,
        fertilizer: 'General houseplant feed',
        nutritionFrequency: 21,
        soilType: 'Rich, well-draining soil',
        notes: 'Umbrella-like leaves; keep out of direct sun.'
    },
    {
        id: '28',
        name: 'Alocasia Polly',
        scientificName: 'Alocasia × amazonica',
        image: 'https://images.unsplash.com/photo-1583911860205-72f8ac8bb8db?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Advanced',
        light: 'Bright indirect',
        waterFrequency: 5,
        waterVolume: 200,
        fertilizer: 'Diluted fertilizer every 2 weeks',
        nutritionFrequency: 14,
        soilType: 'Well-draining mix with perlite',
        notes: 'Striking foliage; needs high humidity.'
    },
    {
        id: '29',
        name: 'Bird\'s Nest Fern',
        scientificName: 'Asplenium nidus',
        image: 'https://images.unsplash.com/photo-1608056858995-b8ad44efbad2?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Low to medium',
        waterFrequency: 5,
        waterVolume: 180,
        fertilizer: 'Diluted balanced liquid fertilizer',
        nutritionFrequency: 21,
        soilType: 'Moist, well-draining soil with peat',
        notes: 'Thrives in humid bathrooms; avoid watering crown.'
    },
    {
        id: '30',
        name: 'Dumb Cane',
        scientificName: 'Dieffenbachia seguine',
        image: 'https://images.unsplash.com/photo-1545486332-9e0999c535b2?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Medium',
        waterFrequency: 6,
        waterVolume: 220,
        fertilizer: 'All-purpose houseplant feed',
        nutritionFrequency: 30,
        soilType: 'Well-draining, loamy soil',
        notes: 'Toxic if ingested; handle with care.'
    },
    {
        id: '31',
        name: 'String of Pearls',
        scientificName: 'Senecio rowleyanus',
        image: 'https://images.unsplash.com/photo-1544986581-efac024faf62?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright indirect',
        waterFrequency: 12,
        waterVolume: 100,
        fertilizer: 'Diluted succulent fertilizer',
        nutritionFrequency: 45,
        soilType: 'Well-draining succulent mix',
        notes: 'Trailing succulent perfect for hanging baskets.'
    },
    {
        id: '32',
        name: 'Haworthia',
        scientificName: 'Haworthia cooperi',
        image: 'https://images.unsplash.com/photo-1509423350716-97f2360af645?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Easy',
        light: 'Bright indirect',
        waterFrequency: 18,
        waterVolume: 80,
        fertilizer: 'Cactus fertilizer',
        nutritionFrequency: 60,
        soilType: 'Cactus and succulent mix',
        notes: 'Small succulent with translucent leaf tips.'
    },
    {
        id: '33',
        name: 'Kentia Palm',
        scientificName: 'Howea forsteriana',
        image: 'https://images.unsplash.com/photo-1586194768530-07cf3fa5b4f1?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Medium',
        waterFrequency: 8,
        waterVolume: 280,
        fertilizer: 'Palm-specific fertilizer',
        nutritionFrequency: 30,
        soilType: 'Well-draining potting mix',
        notes: 'Elegant palm that tolerates low light well.'
    },
    {
        id: '34',
        name: 'String of Hearts',
        scientificName: 'Ceropegia woodii',
        image: 'https://images.unsplash.com/photo-1545486332-9e0999c535b2?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Easy',
        light: 'Bright indirect',
        waterFrequency: 10,
        waterVolume: 120,
        fertilizer: 'Diluted houseplant fertilizer',
        nutritionFrequency: 30,
        soilType: 'Well-draining succulent mix',
        notes: 'Heart-shaped leaves on trailing vines.'
    },
    {
        id: '35',
        name: 'Hoya',
        scientificName: 'Hoya carnosa',
        image: 'https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright indirect',
        waterFrequency: 9,
        waterVolume: 160,
        fertilizer: 'Balanced liquid fertilizer',
        nutritionFrequency: 21,
        soilType: 'Well-draining orchid bark mix',
        notes: 'Waxy flowers and thick succulent-like leaves.'
    },
    {
        id: '36',
        name: 'Ponytail Palm',
        scientificName: 'Beaucarnea recurvata',
        image: 'https://images.unsplash.com/photo-1614592656837-11b46bc26b5b?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Easy',
        light: 'Bright',
        waterFrequency: 16,
        waterVolume: 140,
        fertilizer: 'Balanced houseplant feed',
        nutritionFrequency: 45,
        soilType: 'Well-draining cactus mix',
        notes: 'Stores water in bulbous trunk base.'
    },
    {
        id: '37',
        name: 'Tradescantia',
        scientificName: 'Tradescantia zebrina',
        image: 'https://images.unsplash.com/photo-1583911860205-72f8ac8bb8db?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Easy',
        light: 'Bright indirect',
        waterFrequency: 5,
        waterVolume: 180,
        fertilizer: 'General houseplant fertilizer',
        nutritionFrequency: 28,
        soilType: 'Standard potting mix',
        notes: 'Fast-growing trailing plant with purple stripes.'
    },
    {
        id: '38',
        name: 'Begonia',
        scientificName: 'Begonia rex',
        image: 'https://images.unsplash.com/photo-1608056858995-b8ad44efbad2?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright indirect',
        waterFrequency: 5,
        waterVolume: 200,
        fertilizer: 'Balanced liquid fertilizer',
        nutritionFrequency: 14,
        soilType: 'Peat-based, well-draining mix',
        notes: 'Striking colorful foliage patterns.'
    },
    {
        id: '39',
        name: 'Air Plant',
        scientificName: 'Tillandsia ionantha',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright indirect',
        waterFrequency: 3,
        waterVolume: 0,
        fertilizer: 'Bromeliad fertilizer mist',
        nutritionFrequency: 30,
        soilType: 'No soil - epiphytic',
        notes: 'Mist 2-3 times per week; no soil needed.'
    },
    {
        id: '40',
        name: 'Peperomia',
        scientificName: 'Peperomia obtusifolia',
        image: 'https://images.unsplash.com/photo-1582821431309-317c09bb1a75?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Easy',
        light: 'Medium',
        waterFrequency: 8,
        waterVolume: 140,
        fertilizer: 'Diluted houseplant fertilizer',
        nutritionFrequency: 30,
        soilType: 'Well-draining potting mix',
        notes: 'Compact plant with thick, glossy leaves.'
    },
    {
        id: '41',
        name: 'Bird of Paradise',
        scientificName: 'Strelitzia reginae',
        image: 'https://images.unsplash.com/photo-1544986581-efac024faf62?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Advanced',
        light: 'Bright direct',
        waterFrequency: 6,
        waterVolume: 350,
        fertilizer: 'High-nitrogen fertilizer',
        nutritionFrequency: 14,
        soilType: 'Rich, well-draining soil',
        notes: 'Large leaves may split naturally; needs space.'
    },
    {
        id: '42',
        name: 'Echeveria',
        scientificName: 'Echeveria elegans',
        image: 'https://images.unsplash.com/photo-1509423350716-97f2360af645?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Easy',
        light: 'Bright',
        waterFrequency: 14,
        waterVolume: 100,
        fertilizer: 'Succulent fertilizer',
        nutritionFrequency: 60,
        soilType: 'Cactus and succulent mix',
        notes: 'Rosette-shaped succulent with blue-green leaves.'
    },
    {
        id: '43',
        name: 'Cyclamen',
        scientificName: 'Cyclamen persicum',
        image: 'https://images.unsplash.com/photo-1586194768530-07cf3fa5b4f1?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright indirect',
        waterFrequency: 4,
        waterVolume: 150,
        fertilizer: 'Low-nitrogen flowering fertilizer',
        nutritionFrequency: 21,
        soilType: 'Well-draining, slightly alkaline mix',
        notes: 'Beautiful flowers; prefers cool temperatures.'
    },
    {
        id: '44',
        name: 'Fittonia',
        scientificName: 'Fittonia albivenis',
        image: 'https://images.unsplash.com/photo-1545486332-9e0999c535b2?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Low to medium',
        waterFrequency: 4,
        waterVolume: 130,
        fertilizer: 'Diluted houseplant fertilizer',
        nutritionFrequency: 21,
        soilType: 'Peaty, moisture-retaining mix',
        notes: 'Nerve plant with intricate leaf patterns.'
    },
    {
        id: '45',
        name: 'Lithops',
        scientificName: 'Lithops aucampiae',
        image: 'https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Advanced',
        light: 'Bright',
        waterFrequency: 30,
        waterVolume: 50,
        fertilizer: 'Very diluted cactus fertilizer',
        nutritionFrequency: 90,
        soilType: 'Mineral-rich, very well-draining mix',
        notes: 'Living stones that mimic rocks; water sparingly.'
    },
    {
        id: '46',
        name: 'Sansevieria Cylindrica',
        scientificName: 'Sansevieria cylindrica',
        image: 'https://images.unsplash.com/photo-1614592656837-11b46bc26b5b?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Easy',
        light: 'Low to bright',
        waterFrequency: 20,
        waterVolume: 120,
        fertilizer: 'General houseplant fertilizer',
        nutritionFrequency: 45,
        soilType: 'Well-draining sandy soil',
        notes: 'Cylindrical leaves, very drought tolerant.'
    },
    {
        id: '47',
        name: 'Polka Dot Plant',
        scientificName: 'Hypoestes phyllostachya',
        image: 'https://images.unsplash.com/photo-1583911860205-72f8ac8bb8db?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright indirect',
        waterFrequency: 3,
        waterVolume: 160,
        fertilizer: 'Balanced liquid fertilizer',
        nutritionFrequency: 14,
        soilType: 'Well-draining potting mix',
        notes: 'Colorful spotted leaves; pinch flowers to maintain foliage.'
    },
    {
        id: '48',
        name: 'Staghorn Fern',
        scientificName: 'Platycerium bifurcatum',
        image: 'https://images.unsplash.com/photo-1608056858995-b8ad44efbad2?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Advanced',
        light: 'Bright indirect',
        waterFrequency: 5,
        waterVolume: 200,
        fertilizer: 'Diluted liquid fertilizer',
        nutritionFrequency: 21,
        soilType: 'Mounted on bark or sphagnum moss',
        notes: 'Epiphytic fern; mist regularly for humidity.'
    },
    {
        id: '49',
        name: 'Yucca',
        scientificName: 'Yucca elephantipes',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Easy',
        light: 'Bright',
        waterFrequency: 12,
        waterVolume: 200,
        fertilizer: 'Balanced houseplant fertilizer',
        nutritionFrequency: 30,
        soilType: 'Well-draining sandy mix',
        notes: 'Sword-like leaves on thick trunk; very resilient.'
    },
    {
        id: '50',
        name: 'Bromeliad',
        scientificName: 'Guzmania lingulata',
        image: 'https://images.unsplash.com/photo-1582821431309-317c09bb1a75?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright indirect',
        waterFrequency: 7,
        waterVolume: 150,
        fertilizer: 'Bromeliad fertilizer',
        nutritionFrequency: 28,
        soilType: 'Orchid bark mix',
        notes: 'Water in central cup; colorful bracts.'
    },
    {
        id: '51',
        name: 'Zebra Plant',
        scientificName: 'Aphelandra squarrosa',
        image: 'https://images.unsplash.com/photo-1544986581-efac024faf62?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Advanced',
        light: 'Bright indirect',
        waterFrequency: 4,
        waterVolume: 200,
        fertilizer: 'High-nitrogen fertilizer',
        nutritionFrequency: 14,
        soilType: 'Rich, well-draining potting mix',
        notes: 'White-veined leaves and yellow flower spikes.'
    },
    {
        id: '52',
        name: 'Caladium',
        scientificName: 'Caladium bicolor',
        image: 'https://images.unsplash.com/photo-1509423350716-97f2360af645?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright indirect',
        waterFrequency: 5,
        waterVolume: 180,
        fertilizer: 'Balanced liquid fertilizer',
        nutritionFrequency: 14,
        soilType: 'Rich, well-draining mix',
        notes: 'Heart-shaped leaves with vibrant colors.'
    },
    {
        id: '53',
        name: 'Swiss Cheese Vine',
        scientificName: 'Monstera adansonii',
        image: 'https://images.unsplash.com/photo-1586194768530-07cf3fa5b4f1?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Medium',
        waterFrequency: 6,
        waterVolume: 200,
        fertilizer: 'Balanced houseplant fertilizer',
        nutritionFrequency: 21,
        soilType: 'Aroid mix with good drainage',
        notes: 'Fenestrated leaves; great for hanging baskets.'
    },
    {
        id: '54',
        name: 'Crown of Thorns',
        scientificName: 'Euphorbia milii',
        image: 'https://images.unsplash.com/photo-1545486332-9e0999c535b2?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Easy',
        light: 'Bright',
        waterFrequency: 10,
        waterVolume: 120,
        fertilizer: 'Cactus fertilizer',
        nutritionFrequency: 30,
        soilType: 'Well-draining cactus mix',
        notes: 'Thorny stems with colorful bracts; handle carefully.'
    },
    {
        id: '55',
        name: 'Nerve Plant',
        scientificName: 'Fittonia verschaffeltii',
        image: 'https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Low to medium',
        waterFrequency: 4,
        waterVolume: 130,
        fertilizer: 'Diluted houseplant fertilizer',
        nutritionFrequency: 21,
        soilType: 'Moisture-retaining potting mix',
        notes: 'Dramatic drooping when thirsty; recovers quickly.'
    },
    {
        id: '56',
        name: 'Sago Palm',
        scientificName: 'Cycas revoluta',
        image: 'https://images.unsplash.com/photo-1614592656837-11b46bc26b5b?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright indirect',
        waterFrequency: 10,
        waterVolume: 250,
        fertilizer: 'Palm fertilizer',
        nutritionFrequency: 30,
        soilType: 'Well-draining sandy mix',
        notes: 'Slow-growing cycad; toxic to pets.'
    },
    {
        id: '57',
        name: 'Madagascar Dragon Tree',
        scientificName: 'Dracaena marginata',
        image: 'https://images.unsplash.com/photo-1583911860205-72f8ac8bb8db?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Easy',
        light: 'Medium',
        waterFrequency: 12,
        waterVolume: 180,
        fertilizer: 'General houseplant fertilizer',
        nutritionFrequency: 30,
        soilType: 'Well-draining potting mix',
        notes: 'Narrow leaves with red edges; very adaptable.'
    },
    {
        id: '58',
        name: 'Goldfish Plant',
        scientificName: 'Columnea gloriosa',
        image: 'https://images.unsplash.com/photo-1608056858995-b8ad44efbad2?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright indirect',
        waterFrequency: 6,
        waterVolume: 170,
        fertilizer: 'Balanced liquid fertilizer',
        nutritionFrequency: 14,
        soilType: 'Well-draining potting mix',
        notes: 'Orange tubular flowers resemble goldfish.'
    },
    {
        id: '59',
        name: 'Living Stone',
        scientificName: 'Lithops fulviceps',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Advanced',
        light: 'Bright',
        waterFrequency: 35,
        waterVolume: 40,
        fertilizer: 'Very diluted cactus fertilizer',
        nutritionFrequency: 120,
        soilType: 'Extremely well-draining mineral mix',
        notes: 'Mimics stones; water only during growing season.'
    },
    {
        id: '60',
        name: 'Wax Plant',
        scientificName: 'Hoya australis',
        image: 'https://images.unsplash.com/photo-1509423350716-97f2360af645?w=640&h=960&fit=crop&crop=center',
        careLevel: 'Moderate',
        light: 'Bright indirect',
        waterFrequency: 8,
        waterVolume: 160,
        fertilizer: 'Balanced liquid fertilizer',
        nutritionFrequency: 21,
        soilType: 'Well-draining orchid bark mix',
        notes: 'Fragrant star-shaped flowers; don\'t remove flower spurs.'
    }
];